version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password1234
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # fastapi_app:
  #   build: AI/langchain_agent
  #   container_name: fastapi_server
  #   restart: always
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     MONGODB_ATLAS_CLUSTER_URI: ${MONGODB_ATLAS_CLUSTER_URI}
  #     GROQ_API_KEY: ${GROQ_API_KEY}
  #   depends_on:
  #     - postgres
  minio:
    image: minio/minio
    container_name: minio_server
    restart: always
    ports:
      - "6000:6000"  # API port
      - "6001:6001"  # Web console port
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    volumes:
      - minio_data:/data
    command: server --address ":6000" --console-address ":6001" /data



volumes:
  postgres_data:
  minio_data: