version: '3.9'

networks:
  kafka_net:

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password1234
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: minio_server
    restart: always
    ports:
      - "6000:6000"
      - "6001:6001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    volumes:
      - minio_data:/data
    command: server --address ":6000" --console-address ":6001" /data

  redis:
    image: redis:7.2-alpine
    container_name: redis-server
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis_data:/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    networks:
      - kafka_net
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    container_name: kafka
    networks:
      - kafka_net
    image: confluentinc/cp-kafka:7.6.0
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1




  # kafka-ui:
  #   profiles:
  #     - debug
  #   container_name: kafka-ui
  #   networks:
  #     - kafka_net
  #   image: provectuslabs/kafka-ui:latest
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     KAFKA_CLUSTERS_0_NAME: local
  #     KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
  #   depends_on:
  #     - kafka





  # --- Debug tools ---

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    profiles:
      - debug
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: abc@gmail.com
      PGADMIN_DEFAULT_PASSWORD: debug123

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    profiles:
      - debug
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/data

  # mailhog:
  #   image: mailhog/mailhog
  #   container_name: mailhog
  #   profiles:
  #     - debug
  #   ports:
  #     - "8025:8025"

  # jaeger:
  #   image: jaegertracing/all-in-one:latest
  #   container_name: jaeger
  #   profiles:
  #     - debug
  #   ports:
  #     - "16686:16686"

  # prometheus:
  #   image: prom/prometheus
  #   container_name: prometheus
  #   profiles:
  #     - debug
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml

  # grafana:
  #   image: grafana/grafana
  #   container_name: grafana
  #   profiles:
  #     - debug
  #   ports:
  #     - "3001:3000"

  # portainer:
  #   image: portainer/portainer-ce
  #   container_name: portainer
  #   profiles:
  #     - debug
  #   ports:
  #     - "9000:9000"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - portainer_data:/data

  # netdata:
  #   image: netdata/netdata
  #   container_name: netdata
  #   profiles:
  #     - debug
  #   ports:
  #     - "19999:19999"
  #   cap_add:
  #     - SYS_PTRACE
  #   security_opt:
  #     - apparmor:unconfined

#   kafka-ui:
#     container_name: kafka-ui
#     networks:
#       - kafka_net
#     image: provectuslabs/kafka-ui:latest
#     ports:
#       - "8080:8080"
#     environment:
#       KAFKA_CLUSTERS_0_NAME: local
#       KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
#     depends_on:
#       - kafka

volumes:
  redis_data:
  postgres_data:
  minio_data:
  portainer_data:
  redisinsight_data: