# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"A\n\x14ValidateTokenRequest\x12\x13\n\x0b\x61\x63\x63\x65ssToken\x18\x01 \x01(\t\x12\x14\n\x0crefreshToken\x18\x02 \x01(\t\"j\n\x15ValidateTokenResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t\x12\x13\n\x0b\x61\x63\x63\x65ssToken\x18\x05 \x01(\t\"%\n\x12GetUserByIdRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"~\n\x13GetUserByIdResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x12\n\nfirst_name\x18\x03 \x01(\t\x12\x11\n\tlast_name\x18\x04 \x01(\t\x12\x11\n\tis_active\x18\x05 \x01(\x08\x12\r\n\x05\x65rror\x18\x06 \x01(\t2\x9b\x01\n\x0b\x41uthService\x12H\n\rValidateToken\x12\x1a.auth.ValidateTokenRequest\x1a\x1b.auth.ValidateTokenResponse\x12\x42\n\x0bGetUserById\x12\x18.auth.GetUserByIdRequest\x1a\x19.auth.GetUserByIdResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VALIDATETOKENREQUEST']._serialized_start=20
  _globals['_VALIDATETOKENREQUEST']._serialized_end=85
  _globals['_VALIDATETOKENRESPONSE']._serialized_start=87
  _globals['_VALIDATETOKENRESPONSE']._serialized_end=193
  _globals['_GETUSERBYIDREQUEST']._serialized_start=195
  _globals['_GETUSERBYIDREQUEST']._serialized_end=232
  _globals['_GETUSERBYIDRESPONSE']._serialized_start=234
  _globals['_GETUSERBYIDRESPONSE']._serialized_end=360
  _globals['_AUTHSERVICE']._serialized_start=363
  _globals['_AUTHSERVICE']._serialized_end=518
# @@protoc_insertion_point(module_scope)
